import type { Metadata } from "next";
import { Nunito, Nunito_Sans } from "next/font/google";
import "@/styles/globals.css";
import MainLayout from "@/components/ui/layouts/main-layout";
import { Toaster } from "react-hot-toast";
import QueryProviders from "@/contexts/query-provider";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${nunitoSans.variable} antialiased`}>
        <QueryProviders>
          <MainLayout>{children}</MainLayout>
        </QueryProviders>
        <Toaster
          toastOptions={{
            style: {
              fontSize: "12px",
              fontWeight: "700",
            },

            success: {
              iconTheme: {
                primary: "black",
                secondary: "white",
              },
            },
          }}
          containerStyle={{ zIndex: 2147483647 }}
        />
      </body>
    </html>
  );
}
